name: Support-Server
main: Chanhne.Main_GiftCode
author: Chanhne
version: 1.0.0
api-version: 1.21
depend: [ProtocolLib] 

commands:
  sp:
    description: Quản lý Giftcode (admin)
    usage: /sp <create|delete|reload|enable|disable|list|whitelist|permission|help|?>
    permission: SP.admin
    permission-message: "§cBạn không có quyền sử dụng lệnh này!"
  code:
    description: Sử dụng GIfcode (cho người chơi)
    usage: /code <mã_code>

permissions:
  giftcode.admin:
    description: Admin permissions for Support Server
    default: op